### ISSUE TITLE
Couldn't load gnustl_shared from loader dalvik.system.PathClassLoader

### ISSUE THREAD

**Issue by boeboe** [Audioneex/otasample#1]
When trying the Android sample, I receive the following error:

	04-21 09:52:42.390  15748-15748/com.audioneex.otaexample W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4162edb8)
	04-21 09:52:42.400  15748-15748/com.audioneex.otaexample E/AndroidRuntime﹕ FATAL EXCEPTION: main
		Process: com.audioneex.otaexample, PID: 15748
		java.lang.UnsatisfiedLinkError: Couldn't load gnustl_shared from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.audioneex.otaexample-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.audioneex.otaexample-1, /vendor/lib, /system/lib]]]: findLibrary returned null
				at java.lang.Runtime.loadLibrary(Runtime.java:358)
				at java.lang.System.loadLibrary(System.java:526)
				at com.audioneex.otaexample.OTAFragment.<clinit>(OTAFragment.java:110)
				at com.audioneex.otaexample.MainActivity.onCreate(MainActivity.java:47)
				at android.app.Activity.performCreate(Activity.java:5231)
				at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
				at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
				at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
				at android.app.ActivityThread.access$800(ActivityThread.java:144)
				at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
				at android.os.Handler.dispatchMessage(Handler.java:102)
				at android.os.Looper.loop(Looper.java:136)
				at android.app.ActivityThread.main(ActivityThread.java:5146)
				at java.lang.reflect.Method.invokeNative(Native Method)
				at java.lang.reflect.Method.invoke(Method.java:515)
				at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
				at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
				at dalvik.system.NativeStart.main(Native Method)

Any idea what might be the issue here?

**Comment by boeboe** [comment]
I've got it working in the mean while. The problem was that my JNI build was not properly triggered from within Gradle. Also, one needs to install boost library in /usr/local in order to be able to compile this sample.

I have migrated the project to a Gradle driven project, since I hate using Eclipse.
https://bitbucket.org/boeboe/audioneex-demo

**Comment by a-gram** [comment]
That looked a lot like a Gradle configuration issue. Unfortunately Android Studio was a bit of a pain for native development as it did not directly support the NDK (at least not when i last used it) and you had to configure everything yourself in Gradle, which i hated :)
Thanks for the migration. I will update the rep.
